int32 timestamp
uint32 seq

float32 nav_vx
float32 nav_vy

float32 global_vx
float32 global_vy

float32 x_pre
float32 y_pre
float32 z_pre
float32 varx_pre
float32 vary_pre

float32 dx_pre
float32 dy_pre
float32 dz_pre
float32 vardx_pre
float32 vardy_pre

float32 x_post
float32 y_post
float32 z_post
float32 varx_post
float32 vary_post

float32 dx_post
float32 dy_post
float32 dz_post
float32 vardx_post
float32 vardy_post