/* Auto-generated by genmsg_cpp for file /home/dev/ros/stacks/AutoNav/msg/obs_tag.msg */
#ifndef AUTONAV_MESSAGE_OBS_TAG_H
#define AUTONAV_MESSAGE_OBS_TAG_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace AutoNav
{
template <class ContainerAllocator>
struct obs_tag_ {
  typedef obs_tag_<ContainerAllocator> Type;

  obs_tag_()
  : timestamp(0)
  , seq(0)
  , rejected(0)
  , roll_raw(0.0)
  , pitch_raw(0.0)
  , yaw_raw(0.0)
  , x(0.0)
  , y(0.0)
  , z(0.0)
  , roll(0.0)
  , pitch(0.0)
  , yaw(0.0)
  , x_pre(0.0)
  , y_pre(0.0)
  , z_pre(0.0)
  , dx_pre(0.0)
  , dy_pre(0.0)
  , dz_pre(0.0)
  , roll_pre(0.0)
  , pitch_pre(0.0)
  , yaw_pre(0.0)
  , dyaw_pre(0.0)
  , varx_pre(0.0)
  , vary_pre(0.0)
  , vardx_pre(0.0)
  , vardy_pre(0.0)
  , x_post(0.0)
  , y_post(0.0)
  , z_post(0.0)
  , dx_post(0.0)
  , dy_post(0.0)
  , dz_post(0.0)
  , roll_post(0.0)
  , pitch_post(0.0)
  , yaw_post(0.0)
  , dyaw_post(0.0)
  , varx_post(0.0)
  , vary_post(0.0)
  , vardx_post(0.0)
  , vardy_post(0.0)
  {
  }

  obs_tag_(const ContainerAllocator& _alloc)
  : timestamp(0)
  , seq(0)
  , rejected(0)
  , roll_raw(0.0)
  , pitch_raw(0.0)
  , yaw_raw(0.0)
  , x(0.0)
  , y(0.0)
  , z(0.0)
  , roll(0.0)
  , pitch(0.0)
  , yaw(0.0)
  , x_pre(0.0)
  , y_pre(0.0)
  , z_pre(0.0)
  , dx_pre(0.0)
  , dy_pre(0.0)
  , dz_pre(0.0)
  , roll_pre(0.0)
  , pitch_pre(0.0)
  , yaw_pre(0.0)
  , dyaw_pre(0.0)
  , varx_pre(0.0)
  , vary_pre(0.0)
  , vardx_pre(0.0)
  , vardy_pre(0.0)
  , x_post(0.0)
  , y_post(0.0)
  , z_post(0.0)
  , dx_post(0.0)
  , dy_post(0.0)
  , dz_post(0.0)
  , roll_post(0.0)
  , pitch_post(0.0)
  , yaw_post(0.0)
  , dyaw_post(0.0)
  , varx_post(0.0)
  , vary_post(0.0)
  , vardx_post(0.0)
  , vardy_post(0.0)
  {
  }

  typedef int32_t _timestamp_type;
  int32_t timestamp;

  typedef uint32_t _seq_type;
  uint32_t seq;

  typedef int32_t _rejected_type;
  int32_t rejected;

  typedef float _roll_raw_type;
  float roll_raw;

  typedef float _pitch_raw_type;
  float pitch_raw;

  typedef float _yaw_raw_type;
  float yaw_raw;

  typedef float _x_type;
  float x;

  typedef float _y_type;
  float y;

  typedef float _z_type;
  float z;

  typedef float _roll_type;
  float roll;

  typedef float _pitch_type;
  float pitch;

  typedef float _yaw_type;
  float yaw;

  typedef float _x_pre_type;
  float x_pre;

  typedef float _y_pre_type;
  float y_pre;

  typedef float _z_pre_type;
  float z_pre;

  typedef float _dx_pre_type;
  float dx_pre;

  typedef float _dy_pre_type;
  float dy_pre;

  typedef float _dz_pre_type;
  float dz_pre;

  typedef float _roll_pre_type;
  float roll_pre;

  typedef float _pitch_pre_type;
  float pitch_pre;

  typedef float _yaw_pre_type;
  float yaw_pre;

  typedef float _dyaw_pre_type;
  float dyaw_pre;

  typedef float _varx_pre_type;
  float varx_pre;

  typedef float _vary_pre_type;
  float vary_pre;

  typedef float _vardx_pre_type;
  float vardx_pre;

  typedef float _vardy_pre_type;
  float vardy_pre;

  typedef float _x_post_type;
  float x_post;

  typedef float _y_post_type;
  float y_post;

  typedef float _z_post_type;
  float z_post;

  typedef float _dx_post_type;
  float dx_post;

  typedef float _dy_post_type;
  float dy_post;

  typedef float _dz_post_type;
  float dz_post;

  typedef float _roll_post_type;
  float roll_post;

  typedef float _pitch_post_type;
  float pitch_post;

  typedef float _yaw_post_type;
  float yaw_post;

  typedef float _dyaw_post_type;
  float dyaw_post;

  typedef float _varx_post_type;
  float varx_post;

  typedef float _vary_post_type;
  float vary_post;

  typedef float _vardx_post_type;
  float vardx_post;

  typedef float _vardy_post_type;
  float vardy_post;


  typedef boost::shared_ptr< ::AutoNav::obs_tag_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::AutoNav::obs_tag_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct obs_tag
typedef  ::AutoNav::obs_tag_<std::allocator<void> > obs_tag;

typedef boost::shared_ptr< ::AutoNav::obs_tag> obs_tagPtr;
typedef boost::shared_ptr< ::AutoNav::obs_tag const> obs_tagConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::AutoNav::obs_tag_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::AutoNav::obs_tag_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace AutoNav

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::AutoNav::obs_tag_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::AutoNav::obs_tag_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::AutoNav::obs_tag_<ContainerAllocator> > {
  static const char* value() 
  {
    return "b356b42ccfd53b78fcb593c537f477e4";
  }

  static const char* value(const  ::AutoNav::obs_tag_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xb356b42ccfd53b78ULL;
  static const uint64_t static_value2 = 0xfcb593c537f477e4ULL;
};

template<class ContainerAllocator>
struct DataType< ::AutoNav::obs_tag_<ContainerAllocator> > {
  static const char* value() 
  {
    return "AutoNav/obs_tag";
  }

  static const char* value(const  ::AutoNav::obs_tag_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::AutoNav::obs_tag_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int32 timestamp\n\
uint32 seq\n\
\n\
int32 rejected\n\
\n\
float32 roll_raw\n\
float32 pitch_raw\n\
float32 yaw_raw\n\
\n\
# the observation\n\
float32 x\n\
float32 y\n\
float32 z\n\
float32 roll\n\
float32 pitch\n\
float32 yaw\n\
\n\
#the prior\n\
float32 x_pre\n\
float32 y_pre\n\
float32 z_pre\n\
float32 dx_pre\n\
float32 dy_pre\n\
float32 dz_pre\n\
float32 roll_pre\n\
float32 pitch_pre\n\
float32 yaw_pre\n\
float32 dyaw_pre\n\
float32 varx_pre\n\
float32 vary_pre\n\
float32 vardx_pre\n\
float32 vardy_pre\n\
\n\
#the posterior\n\
float32 x_post\n\
float32 y_post\n\
float32 z_post\n\
float32 dx_post\n\
float32 dy_post\n\
float32 dz_post\n\
float32 roll_post\n\
float32 pitch_post\n\
float32 yaw_post\n\
float32 dyaw_post\n\
float32 varx_post\n\
float32 vary_post\n\
float32 vardx_post\n\
float32 vardy_post\n\
";
  }

  static const char* value(const  ::AutoNav::obs_tag_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::AutoNav::obs_tag_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::AutoNav::obs_tag_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.timestamp);
    stream.next(m.seq);
    stream.next(m.rejected);
    stream.next(m.roll_raw);
    stream.next(m.pitch_raw);
    stream.next(m.yaw_raw);
    stream.next(m.x);
    stream.next(m.y);
    stream.next(m.z);
    stream.next(m.roll);
    stream.next(m.pitch);
    stream.next(m.yaw);
    stream.next(m.x_pre);
    stream.next(m.y_pre);
    stream.next(m.z_pre);
    stream.next(m.dx_pre);
    stream.next(m.dy_pre);
    stream.next(m.dz_pre);
    stream.next(m.roll_pre);
    stream.next(m.pitch_pre);
    stream.next(m.yaw_pre);
    stream.next(m.dyaw_pre);
    stream.next(m.varx_pre);
    stream.next(m.vary_pre);
    stream.next(m.vardx_pre);
    stream.next(m.vardy_pre);
    stream.next(m.x_post);
    stream.next(m.y_post);
    stream.next(m.z_post);
    stream.next(m.dx_post);
    stream.next(m.dy_post);
    stream.next(m.dz_post);
    stream.next(m.roll_post);
    stream.next(m.pitch_post);
    stream.next(m.yaw_post);
    stream.next(m.dyaw_post);
    stream.next(m.varx_post);
    stream.next(m.vary_post);
    stream.next(m.vardx_post);
    stream.next(m.vardy_post);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct obs_tag_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::AutoNav::obs_tag_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::AutoNav::obs_tag_<ContainerAllocator> & v) 
  {
    s << indent << "timestamp: ";
    Printer<int32_t>::stream(s, indent + "  ", v.timestamp);
    s << indent << "seq: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.seq);
    s << indent << "rejected: ";
    Printer<int32_t>::stream(s, indent + "  ", v.rejected);
    s << indent << "roll_raw: ";
    Printer<float>::stream(s, indent + "  ", v.roll_raw);
    s << indent << "pitch_raw: ";
    Printer<float>::stream(s, indent + "  ", v.pitch_raw);
    s << indent << "yaw_raw: ";
    Printer<float>::stream(s, indent + "  ", v.yaw_raw);
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<float>::stream(s, indent + "  ", v.z);
    s << indent << "roll: ";
    Printer<float>::stream(s, indent + "  ", v.roll);
    s << indent << "pitch: ";
    Printer<float>::stream(s, indent + "  ", v.pitch);
    s << indent << "yaw: ";
    Printer<float>::stream(s, indent + "  ", v.yaw);
    s << indent << "x_pre: ";
    Printer<float>::stream(s, indent + "  ", v.x_pre);
    s << indent << "y_pre: ";
    Printer<float>::stream(s, indent + "  ", v.y_pre);
    s << indent << "z_pre: ";
    Printer<float>::stream(s, indent + "  ", v.z_pre);
    s << indent << "dx_pre: ";
    Printer<float>::stream(s, indent + "  ", v.dx_pre);
    s << indent << "dy_pre: ";
    Printer<float>::stream(s, indent + "  ", v.dy_pre);
    s << indent << "dz_pre: ";
    Printer<float>::stream(s, indent + "  ", v.dz_pre);
    s << indent << "roll_pre: ";
    Printer<float>::stream(s, indent + "  ", v.roll_pre);
    s << indent << "pitch_pre: ";
    Printer<float>::stream(s, indent + "  ", v.pitch_pre);
    s << indent << "yaw_pre: ";
    Printer<float>::stream(s, indent + "  ", v.yaw_pre);
    s << indent << "dyaw_pre: ";
    Printer<float>::stream(s, indent + "  ", v.dyaw_pre);
    s << indent << "varx_pre: ";
    Printer<float>::stream(s, indent + "  ", v.varx_pre);
    s << indent << "vary_pre: ";
    Printer<float>::stream(s, indent + "  ", v.vary_pre);
    s << indent << "vardx_pre: ";
    Printer<float>::stream(s, indent + "  ", v.vardx_pre);
    s << indent << "vardy_pre: ";
    Printer<float>::stream(s, indent + "  ", v.vardy_pre);
    s << indent << "x_post: ";
    Printer<float>::stream(s, indent + "  ", v.x_post);
    s << indent << "y_post: ";
    Printer<float>::stream(s, indent + "  ", v.y_post);
    s << indent << "z_post: ";
    Printer<float>::stream(s, indent + "  ", v.z_post);
    s << indent << "dx_post: ";
    Printer<float>::stream(s, indent + "  ", v.dx_post);
    s << indent << "dy_post: ";
    Printer<float>::stream(s, indent + "  ", v.dy_post);
    s << indent << "dz_post: ";
    Printer<float>::stream(s, indent + "  ", v.dz_post);
    s << indent << "roll_post: ";
    Printer<float>::stream(s, indent + "  ", v.roll_post);
    s << indent << "pitch_post: ";
    Printer<float>::stream(s, indent + "  ", v.pitch_post);
    s << indent << "yaw_post: ";
    Printer<float>::stream(s, indent + "  ", v.yaw_post);
    s << indent << "dyaw_post: ";
    Printer<float>::stream(s, indent + "  ", v.dyaw_post);
    s << indent << "varx_post: ";
    Printer<float>::stream(s, indent + "  ", v.varx_post);
    s << indent << "vary_post: ";
    Printer<float>::stream(s, indent + "  ", v.vary_post);
    s << indent << "vardx_post: ";
    Printer<float>::stream(s, indent + "  ", v.vardx_post);
    s << indent << "vardy_post: ";
    Printer<float>::stream(s, indent + "  ", v.vardy_post);
  }
};


} // namespace message_operations
} // namespace ros

#endif // AUTONAV_MESSAGE_OBS_TAG_H

