######################################################################
# Automatically generated by qmake (2.01a) Fri Feb 15 17:31:57 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Teleop.h
SOURCES += Teleop.cpp
