(cl:in-package AutoNav-msg)
(cl:export '(YAW-VAL
          YAW
          GOALX-VAL
          GOALX
          GOALY-VAL
          GOALY
          ERRORX-VAL
          ERRORX
          ERRORY-VAL
          ERRORY
          PERRORX-VAL
          PERRORX
          PERRORY-VAL
          PERRORY
          PVELX-VAL
          PVELX
          PVELY-VAL
          PVELY
          VERRX-VAL
          VERRX
          VERRY-VAL
          VERRY
          VERRA-VAL
          VERRA
          CTGAINP-VAL
          CTGAINP
          CTGAIND-VAL
          CTGAIND
          ATGAINP-VAL
          ATGAINP
          ATGAINI-VAL
          ATGAINI
          ANGGAINP-VAL
          ANGGAINP
          ANGGAIND-VAL
          ANGGAIND
))