(cl:in-package AutoNav-msg)
(cl:export '(ERROR_X-VAL
          ERROR_X
          ERROR_Y-VAL
          ERROR_Y
          ERROR_Z-VAL
          ERROR_Z
          ERROR_YAW-VAL
          ERROR_YAW
          D_ERROR_X-VAL
          D_ERROR_X
          D_ERROR_Y-VAL
          D_ERROR_Y
          D_ERROR_Z-VAL
          D_ERROR_Z
          D_ERROR_YAW-VAL
          D_ERROR_YAW
          PROJ_ERROR_X-VAL
          PROJ_ERROR_X
          PROJ_ERROR_Y-VAL
          PROJ_ERROR_Y
          PTERM_X-VAL
          PTERM_X
          PTERM_Y-VAL
          PTERM_Y
          PTERM_Z-VAL
          PTERM_Z
          PTERM_YAW-VAL
          PTERM_YAW
          DTERM_X-VAL
          DTERM_X
          DTERM_Y-VAL
          DTERM_Y
          DTERM_Z-VAL
          DTERM_Z
          DTERM_YAW-VAL
          DTERM_YAW
          VEL_X-VAL
          VEL_X
          VEL_Y-VAL
          VEL_Y
          VEL_Z-VAL
          VEL_Z
          VEL_YAW-VAL
          VEL_YAW
))