(cl:in-package AutoNav-msg)
(cl:export '(TIMESTAMP-VAL
          TIMESTAMP
          SEQ-VAL
          SEQ
          ROLL-VAL
          ROLL
          PITCH-VAL
          PITCH
          BASELINEY_IMU-VAL
          BASELINEY_IMU
          BASELINEY_FILTER-VAL
          BASELINEY_FILTER
          NAVYAW-VAL
          NAVYAW
          OBSERVEDYAW-VAL
          OBSERVEDYAW
          ROLL_PRE-VAL
          ROLL_PRE
          PITCH_PRE-VAL
          PITCH_PRE
          YAW_PRE-VAL
          YAW_PRE
          DYAW_PRE-VAL
          DYAW_PRE
          ROLL_POST-VAL
          ROLL_POST
          PITCH_POST-VAL
          PITCH_POST
          YAW_POST-VAL
          YAW_POST
          DYAW_POST-VAL
          DYAW_POST
))