(cl:in-package AutoNav-msg)
(cl:export '(TIMESTAMP-VAL
          TIMESTAMP
          SEQ-VAL
          SEQ
          REJECTED-VAL
          REJECTED
          ROLL_RAW-VAL
          ROLL_RAW
          PITCH_RAW-VAL
          PITCH_RAW
          YAW_RAW-VAL
          YAW_RAW
          X_RAW-VAL
          X_RAW
          Y_RAW-VAL
          Y_RAW
          X-VAL
          X
          Y-VAL
          Y
          Z-VAL
          Z
          ROLL-VAL
          ROLL
          PITCH-VAL
          PITCH
          YAW-VAL
          YAW
          X_PRE-VAL
          X_PRE
          Y_PRE-VAL
          Y_PRE
          Z_PRE-VAL
          Z_PRE
          DX_PRE-VAL
          DX_PRE
          DY_PRE-VAL
          DY_PRE
          DZ_PRE-VAL
          DZ_PRE
          ROLL_PRE-VAL
          ROLL_PRE
          PITCH_PRE-VAL
          PITCH_PRE
          YAW_PRE-VAL
          YAW_PRE
          DYAW_PRE-VAL
          DYAW_PRE
          VARX_PRE-VAL
          VARX_PRE
          VARY_PRE-VAL
          VARY_PRE
          VARDX_PRE-VAL
          VARDX_PRE
          VARDY_PRE-VAL
          VARDY_PRE
          X_POST-VAL
          X_POST
          Y_POST-VAL
          Y_POST
          Z_POST-VAL
          Z_POST
          DX_POST-VAL
          DX_POST
          DY_POST-VAL
          DY_POST
          DZ_POST-VAL
          DZ_POST
          ROLL_POST-VAL
          ROLL_POST
          PITCH_POST-VAL
          PITCH_POST
          YAW_POST-VAL
          YAW_POST
          DYAW_POST-VAL
          DYAW_POST
          VARX_POST-VAL
          VARX_POST
          VARY_POST-VAL
          VARY_POST
          VARDX_POST-VAL
          VARDX_POST
          VARDY_POST-VAL
          VARDY_POST
))