(cl:defpackage AutoNav-msg
  (:use )
  (:export
   "<PREDICTINTERNAL>"
   "PREDICTINTERNAL"
   "<CIRCLE_CONTROL>"
   "CIRCLE_CONTROL"
   "<FILTER_STATE>"
   "FILTER_STATE"
   "<OFFSETS>"
   "OFFSETS"
   "<CONTROL_COMMANDS>"
   "CONTROL_COMMANDS"
   "<OBS_IMU_XYZ>"
   "OBS_IMU_XYZ"
   "<OBS_IMU_RPY>"
   "OBS_IMU_RPY"
   "<EULERPOSE>"
   "EULERPOSE"
   "<OBS_TAG>"
   "OBS_TAG"
   "<PREDICTUPTO>"
   "PREDICTUPTO"
  ))

