(cl:in-package AutoNav-msg)
(cl:export '(TIMESTAMP-VAL
          TIMESTAMP
          TIMESPANMICROS-VAL
          TIMESPANMICROS
          ACTIVECONTROLINFO-VAL
          ACTIVECONTROLINFO
          USECONTROLGAINS-VAL
          USECONTROLGAINS
          CONTROLVALID-VAL
          CONTROLVALID
          ROLLCONTROLGAIN-VAL
          ROLLCONTROLGAIN
          PITCHCONTROLGAIN-VAL
          PITCHCONTROLGAIN
          YAWSPEEDCONTROLGAIN-VAL
          YAWSPEEDCONTROLGAIN
          FORCEX-VAL
          FORCEX
          FORCEY-VAL
          FORCEY
          VX_GAIN-VAL
          VX_GAIN
          VY_GAIN-VAL
          VY_GAIN
          VZ_GAIN-VAL
          VZ_GAIN
          ROLL_PRE-VAL
          ROLL_PRE
          PITCH_PRE-VAL
          PITCH_PRE
          YAW_PRE-VAL
          YAW_PRE
          DYAW_PRE-VAL
          DYAW_PRE
          X_PRE-VAL
          X_PRE
          DX_PRE-VAL
          DX_PRE
          Y_PRE-VAL
          Y_PRE
          DY_PRE-VAL
          DY_PRE
          Z_PRE-VAL
          Z_PRE
          DZ_PRE-VAL
          DZ_PRE
          VARX_PRE-VAL
          VARX_PRE
          VARY_PRE-VAL
          VARY_PRE
          VARDX_PRE-VAL
          VARDX_PRE
          VARDY_PRE-VAL
          VARDY_PRE
          ROLL_POST-VAL
          ROLL_POST
          PITCH_POST-VAL
          PITCH_POST
          YAW_POST-VAL
          YAW_POST
          DYAW_POST-VAL
          DYAW_POST
          X_POST-VAL
          X_POST
          DX_POST-VAL
          DX_POST
          Y_POST-VAL
          Y_POST
          DY_POST-VAL
          DY_POST
          Z_POST-VAL
          Z_POST
          DZ_POST-VAL
          DZ_POST
          VARX_POST-VAL
          VARX_POST
          VARY_POST-VAL
          VARY_POST
          VARDX_POST-VAL
          VARDX_POST
          VARDY_POST-VAL
          VARDY_POST
))