"""autogenerated by genpy from AutoNav/predictInternal.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg

class predictInternal(genpy.Message):
  _md5sum = "ecda137da737bf0c26f0e9aeaeab8110"
  _type = "AutoNav/predictInternal"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """#time when message was published
int32 timestamp

int32 timeSpanMicros

geometry_msgs/Twist activeControlInfo

int32 useControlGains
int32 controlValid

# gains because of given Control Commands
float32 rollControlGain
float32 pitchControlGain
float32 yawSpeedControlGain

#Forces project on horizontal axes due to tilt
float32 forceX
float32 forceY

#Velocity gain due to forces on horizontal axes
float32 vx_gain
float32 vy_gain
float32 vz_gain

#prior state before prediction
float32 roll_pre
float32 pitch_pre
float32 yaw_pre
float32 dyaw_pre
float32 x_pre
float32 dx_pre
float32 y_pre
float32 dy_pre
float32 z_pre
float32 dz_pre
float32 varx_pre
float32 vary_pre
float32 vardx_pre
float32 vardy_pre

#posterior state after prediction
float32 roll_post
float32 pitch_post
float32 yaw_post
float32 dyaw_post
float32 x_post
float32 dx_post
float32 y_post
float32 dy_post
float32 z_post
float32 dz_post
float32 varx_post
float32 vary_post
float32 vardx_post
float32 vardy_post

================================================================================
MSG: geometry_msgs/Twist
# This expresses velocity in free space broken into it's linear and angular parts. 
Vector3  linear
Vector3  angular

================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 

float64 x
float64 y
float64 z
"""
  __slots__ = ['timestamp','timeSpanMicros','activeControlInfo','useControlGains','controlValid','rollControlGain','pitchControlGain','yawSpeedControlGain','forceX','forceY','vx_gain','vy_gain','vz_gain','roll_pre','pitch_pre','yaw_pre','dyaw_pre','x_pre','dx_pre','y_pre','dy_pre','z_pre','dz_pre','varx_pre','vary_pre','vardx_pre','vardy_pre','roll_post','pitch_post','yaw_post','dyaw_post','x_post','dx_post','y_post','dy_post','z_post','dz_post','varx_post','vary_post','vardx_post','vardy_post']
  _slot_types = ['int32','int32','geometry_msgs/Twist','int32','int32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       timestamp,timeSpanMicros,activeControlInfo,useControlGains,controlValid,rollControlGain,pitchControlGain,yawSpeedControlGain,forceX,forceY,vx_gain,vy_gain,vz_gain,roll_pre,pitch_pre,yaw_pre,dyaw_pre,x_pre,dx_pre,y_pre,dy_pre,z_pre,dz_pre,varx_pre,vary_pre,vardx_pre,vardy_pre,roll_post,pitch_post,yaw_post,dyaw_post,x_post,dx_post,y_post,dy_post,z_post,dz_post,varx_post,vary_post,vardx_post,vardy_post

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(predictInternal, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.timestamp is None:
        self.timestamp = 0
      if self.timeSpanMicros is None:
        self.timeSpanMicros = 0
      if self.activeControlInfo is None:
        self.activeControlInfo = geometry_msgs.msg.Twist()
      if self.useControlGains is None:
        self.useControlGains = 0
      if self.controlValid is None:
        self.controlValid = 0
      if self.rollControlGain is None:
        self.rollControlGain = 0.
      if self.pitchControlGain is None:
        self.pitchControlGain = 0.
      if self.yawSpeedControlGain is None:
        self.yawSpeedControlGain = 0.
      if self.forceX is None:
        self.forceX = 0.
      if self.forceY is None:
        self.forceY = 0.
      if self.vx_gain is None:
        self.vx_gain = 0.
      if self.vy_gain is None:
        self.vy_gain = 0.
      if self.vz_gain is None:
        self.vz_gain = 0.
      if self.roll_pre is None:
        self.roll_pre = 0.
      if self.pitch_pre is None:
        self.pitch_pre = 0.
      if self.yaw_pre is None:
        self.yaw_pre = 0.
      if self.dyaw_pre is None:
        self.dyaw_pre = 0.
      if self.x_pre is None:
        self.x_pre = 0.
      if self.dx_pre is None:
        self.dx_pre = 0.
      if self.y_pre is None:
        self.y_pre = 0.
      if self.dy_pre is None:
        self.dy_pre = 0.
      if self.z_pre is None:
        self.z_pre = 0.
      if self.dz_pre is None:
        self.dz_pre = 0.
      if self.varx_pre is None:
        self.varx_pre = 0.
      if self.vary_pre is None:
        self.vary_pre = 0.
      if self.vardx_pre is None:
        self.vardx_pre = 0.
      if self.vardy_pre is None:
        self.vardy_pre = 0.
      if self.roll_post is None:
        self.roll_post = 0.
      if self.pitch_post is None:
        self.pitch_post = 0.
      if self.yaw_post is None:
        self.yaw_post = 0.
      if self.dyaw_post is None:
        self.dyaw_post = 0.
      if self.x_post is None:
        self.x_post = 0.
      if self.dx_post is None:
        self.dx_post = 0.
      if self.y_post is None:
        self.y_post = 0.
      if self.dy_post is None:
        self.dy_post = 0.
      if self.z_post is None:
        self.z_post = 0.
      if self.dz_post is None:
        self.dz_post = 0.
      if self.varx_post is None:
        self.varx_post = 0.
      if self.vary_post is None:
        self.vary_post = 0.
      if self.vardx_post is None:
        self.vardx_post = 0.
      if self.vardy_post is None:
        self.vardy_post = 0.
    else:
      self.timestamp = 0
      self.timeSpanMicros = 0
      self.activeControlInfo = geometry_msgs.msg.Twist()
      self.useControlGains = 0
      self.controlValid = 0
      self.rollControlGain = 0.
      self.pitchControlGain = 0.
      self.yawSpeedControlGain = 0.
      self.forceX = 0.
      self.forceY = 0.
      self.vx_gain = 0.
      self.vy_gain = 0.
      self.vz_gain = 0.
      self.roll_pre = 0.
      self.pitch_pre = 0.
      self.yaw_pre = 0.
      self.dyaw_pre = 0.
      self.x_pre = 0.
      self.dx_pre = 0.
      self.y_pre = 0.
      self.dy_pre = 0.
      self.z_pre = 0.
      self.dz_pre = 0.
      self.varx_pre = 0.
      self.vary_pre = 0.
      self.vardx_pre = 0.
      self.vardy_pre = 0.
      self.roll_post = 0.
      self.pitch_post = 0.
      self.yaw_post = 0.
      self.dyaw_post = 0.
      self.x_post = 0.
      self.dx_post = 0.
      self.y_post = 0.
      self.dy_post = 0.
      self.z_post = 0.
      self.dz_post = 0.
      self.varx_post = 0.
      self.vary_post = 0.
      self.vardx_post = 0.
      self.vardy_post = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_2i6d2i36f.pack(_x.timestamp, _x.timeSpanMicros, _x.activeControlInfo.linear.x, _x.activeControlInfo.linear.y, _x.activeControlInfo.linear.z, _x.activeControlInfo.angular.x, _x.activeControlInfo.angular.y, _x.activeControlInfo.angular.z, _x.useControlGains, _x.controlValid, _x.rollControlGain, _x.pitchControlGain, _x.yawSpeedControlGain, _x.forceX, _x.forceY, _x.vx_gain, _x.vy_gain, _x.vz_gain, _x.roll_pre, _x.pitch_pre, _x.yaw_pre, _x.dyaw_pre, _x.x_pre, _x.dx_pre, _x.y_pre, _x.dy_pre, _x.z_pre, _x.dz_pre, _x.varx_pre, _x.vary_pre, _x.vardx_pre, _x.vardy_pre, _x.roll_post, _x.pitch_post, _x.yaw_post, _x.dyaw_post, _x.x_post, _x.dx_post, _x.y_post, _x.dy_post, _x.z_post, _x.dz_post, _x.varx_post, _x.vary_post, _x.vardx_post, _x.vardy_post))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.activeControlInfo is None:
        self.activeControlInfo = geometry_msgs.msg.Twist()
      end = 0
      _x = self
      start = end
      end += 208
      (_x.timestamp, _x.timeSpanMicros, _x.activeControlInfo.linear.x, _x.activeControlInfo.linear.y, _x.activeControlInfo.linear.z, _x.activeControlInfo.angular.x, _x.activeControlInfo.angular.y, _x.activeControlInfo.angular.z, _x.useControlGains, _x.controlValid, _x.rollControlGain, _x.pitchControlGain, _x.yawSpeedControlGain, _x.forceX, _x.forceY, _x.vx_gain, _x.vy_gain, _x.vz_gain, _x.roll_pre, _x.pitch_pre, _x.yaw_pre, _x.dyaw_pre, _x.x_pre, _x.dx_pre, _x.y_pre, _x.dy_pre, _x.z_pre, _x.dz_pre, _x.varx_pre, _x.vary_pre, _x.vardx_pre, _x.vardy_pre, _x.roll_post, _x.pitch_post, _x.yaw_post, _x.dyaw_post, _x.x_post, _x.dx_post, _x.y_post, _x.dy_post, _x.z_post, _x.dz_post, _x.varx_post, _x.vary_post, _x.vardx_post, _x.vardy_post,) = _struct_2i6d2i36f.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_2i6d2i36f.pack(_x.timestamp, _x.timeSpanMicros, _x.activeControlInfo.linear.x, _x.activeControlInfo.linear.y, _x.activeControlInfo.linear.z, _x.activeControlInfo.angular.x, _x.activeControlInfo.angular.y, _x.activeControlInfo.angular.z, _x.useControlGains, _x.controlValid, _x.rollControlGain, _x.pitchControlGain, _x.yawSpeedControlGain, _x.forceX, _x.forceY, _x.vx_gain, _x.vy_gain, _x.vz_gain, _x.roll_pre, _x.pitch_pre, _x.yaw_pre, _x.dyaw_pre, _x.x_pre, _x.dx_pre, _x.y_pre, _x.dy_pre, _x.z_pre, _x.dz_pre, _x.varx_pre, _x.vary_pre, _x.vardx_pre, _x.vardy_pre, _x.roll_post, _x.pitch_post, _x.yaw_post, _x.dyaw_post, _x.x_post, _x.dx_post, _x.y_post, _x.dy_post, _x.z_post, _x.dz_post, _x.varx_post, _x.vary_post, _x.vardx_post, _x.vardy_post))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.activeControlInfo is None:
        self.activeControlInfo = geometry_msgs.msg.Twist()
      end = 0
      _x = self
      start = end
      end += 208
      (_x.timestamp, _x.timeSpanMicros, _x.activeControlInfo.linear.x, _x.activeControlInfo.linear.y, _x.activeControlInfo.linear.z, _x.activeControlInfo.angular.x, _x.activeControlInfo.angular.y, _x.activeControlInfo.angular.z, _x.useControlGains, _x.controlValid, _x.rollControlGain, _x.pitchControlGain, _x.yawSpeedControlGain, _x.forceX, _x.forceY, _x.vx_gain, _x.vy_gain, _x.vz_gain, _x.roll_pre, _x.pitch_pre, _x.yaw_pre, _x.dyaw_pre, _x.x_pre, _x.dx_pre, _x.y_pre, _x.dy_pre, _x.z_pre, _x.dz_pre, _x.varx_pre, _x.vary_pre, _x.vardx_pre, _x.vardy_pre, _x.roll_post, _x.pitch_post, _x.yaw_post, _x.dyaw_post, _x.x_post, _x.dx_post, _x.y_post, _x.dy_post, _x.z_post, _x.dz_post, _x.varx_post, _x.vary_post, _x.vardx_post, _x.vardy_post,) = _struct_2i6d2i36f.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_2i6d2i36f = struct.Struct("<2i6d2i36f")
